---
name: CI

# https://github.com/actions/virtual-environments#available-environments

'on': [push, pull_request, workflow_dispatch]

jobs:
  test:
    name: >-
      test ${{ matrix.os }} ${{ matrix.ruby }}
    env:
      TESTOPTS: -v

    runs-on: ${{ matrix.os }}
    if: |
      !(   contains(github.event.pull_request.title,  '[ci skip]')
        || contains(github.event.pull_request.title,  '[skip ci]'))
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        ruby:
          - '2.2'
          - '2.3'
          - '2.4'
          - '2.5'
          - '2.6'
          - '2.7'
          - '3.0'
          - '3.1'
          - head

    steps:
      - name: repo checkout
        uses: actions/checkout@v2

      - name: load ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none

      - name: install hoe
        run: gem install hoe -N

      - name: rake test
        run: |
          rake test
        timeout-minutes: 3

  isolated:
    name: >-
      test:isolated ${{ matrix.os }} ${{ matrix.ruby }}
    env:
      TESTOPTS: -v

    runs-on: ${{ matrix.os }}
    if: |
      !(   contains(github.event.pull_request.title,  '[ci skip]')
        || contains(github.event.pull_request.title,  '[skip ci]'))
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ruby:
          - '3.1'
    steps:
      - name: repo checkout
        uses: actions/checkout@v2

      - name: load ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none

      - name: install hoe
        run: gem install hoe -N

      - name: rake test:isolated
        run: |
          rake test:isolated
        timeout-minutes: 3
